AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for circuit breaker pattern

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        paths:
          /catalog:
            get:
              responses:
                '200':
                  description: successful operation
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:states:action/StartExecution
                httpMethod: POST
                type: aws
                credentials: !GetAtt ApiGatewayRole.Arn
                requestTemplates:
                  application/json: |
                    {
                      "stateMachineArn": "arn:aws:states:us-east-1:824949725598:stateMachine:CircuitBreakerStateMachine-J8DXVROnrcR1",
                      "input": "$util.escapeJavaScript('{ \"TargetLambda\": \"arn:aws:lambda:us-east-1:824949725598:function:LesaLjubljanaServerless-GetAndSearchProductsFuncti-Yvvh4M4ci1FV\", \"queryParams\": { \"queryStringParameters\": ' + ($input.json('$params') || '{}') + ' } }')"
                    }
                responseTemplates:
                  application/json: |
                    #set($inputRoot = $input.json('$.Payload.body'))
                    $inputRoot

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ApiGatewayAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: "*"


  SharedLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLibrariesLayer
      Description: Layer for shared libraries
      ContentUri: ServerlessFunction/src/main/java/lib/
      CompatibleRuntimes:
        - java11
      RetentionPolicy: Retain

  GetAndSearchProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServerlessFunction
      Handler: serverless.CatalogProduct.GetAndSearchProducts::handleRequest
      Runtime: java11
      MemorySize: 512
      Tracing: Active
      Policies:
        - AmazonDynamoDBFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - arn:aws:ssm:us-east-1:824949725598:parameter/USER_POOL_ID
                - arn:aws:ssm:us-east-1:824949725598:parameter/CLIENT_APP_ID
                - arn:aws:ssm:us-east-1:824949725598:parameter/DYNAMO_REGION
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: "*"
            - Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
              Resource: "*"
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Layers:
        - !Ref SharedLibrariesLayer


  CircuitBreakerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/circuitbreaker.asl.json
      DefinitionSubstitutions:
        GetCircuitStatusFunctionArn: !GetAtt GetCircuitStatusFunction.Arn
        UpdateCircuitStatusFunctionArn: !GetAtt UpdateCircuitStatusFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref CircuitBreakerTable
      Policies:
        - AWSLambdaRole
        - DynamoDBWritePolicy:
            TableName: !Ref CircuitBreakerTable

  GetCircuitStatusFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./GetCircuitStatusLambda/src/GetCircuitStatusLambda/
      Handler: GetCircuitStatusLambda::GetCircuitStatusLambda.GetCircuitStatus::FunctionHandler
      Runtime: dotnet6
      MemorySize: 256
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
        - AWSXrayFullAccess
        - AWSStepFunctionsFullAccess


  UpdateCircuitStatusFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./UpdateCircuitStatusLambda/src/UpdateCircuitStatusLambda/
      Handler: UpdateCircuitStatusLambda::UpdateCircuitStatusLambda.UpdateCircuitStatus::FunctionHandler
      Runtime: dotnet6
      MemorySize: 256
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
        - AWSXrayFullAccess
        - AWSStepFunctionsFullAccess      

  TestCircuitBreakerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./TestCircuitBreaker/src/TestCircuitBreaker/
      Handler: TestCircuitBreaker::TestCircuitBreaker.Function::FunctionHandler
      Runtime: dotnet6
      MemorySize: 256
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
        - AWSXrayFullAccess
        - AWSStepFunctionsFullAccess
  



  CircuitBreakerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CircuitBreaker
      KeySchema:
        - AttributeName: ServiceName
          KeyType: HASH
        - AttributeName: ExpireTimeStamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: ServiceName
          AttributeType: S
        - AttributeName: ExpireTimeStamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: ExpireTimeStamp
        Enabled: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
      
